### ISSUE TITLE
Issue setting Valid OAuth Redirect URLs to include callback

### ISSUE THREAD

**Issue by medwards1771** [learn-co-curriculum/devise_lab#12]
Hey Guys!

Having some issues with this direction:

You'll also need to go to Settings > Advanced and set Valid OAuth Redirect URLs to include http://localhost:3000/users/auth/facebook/callback. This setting is listed under Client OAuth Settings in the dashboard

It appears Facebook has updated their developer page recently. Neither the dashboard nor the advanced settings page allows you to do anything with Client OAuth Settings. 

Best,
Meredith

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by mendelB** [comment]
@medwards1771 Thanks for raising this issue! This has been updated and clarified here #23
