### ISSUE TITLE
Click-less Specs && Ambiguous matches

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/devise_lab#2]
`spec/features/users/sign_in_spec.rb` was missing the following line:

```
click_button 'Log in'
```

on lines:
16
28
40
52
see link below for implementation
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

`spec/features/users/sign_out_spec.rb` was missing:

```
click_link 'Sign in'
```

on line 14.
see link below for implementation
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

`pec/features/visitors/sign_up_spec.rb` uses this format to sign-up:

```
sign_up_with('test@example.com', 'please123', 'please123')
```

The problem is that it raises the following error because there is a button in the layout with the name text as the form 'Sign up':

```
Failures:

  1) Sign Up visitor cannot sign up without password
     Failure/Error: sign_up_with('test@example.com', 'please123', 'please123')
     Capybara::Ambiguous:
       Ambiguous match, found 2 elements matching button "Sign up"
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/capybara-2.4.4/lib/capybara/node/finders.rb:38:in `block in find'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/capybara-2.4.4/lib/capybara/node/base.rb:84:in `synchronize'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/capybara-2.4.4/lib/capybara/node/finders.rb:30:in `find'

```

One fix is to use the long version. This example works:

```
scenario 'visitor can sign up with valid email address and password' do
   visit new_user_registration_path
      fill_in 'user_email', with: 'test@example.com'
      fill_in 'user_password', with: 'please123'
      fill_in 'user_password_confirmation', with: 'please123'
      within('.new_user') do
        click_button 'Sign up'
      end
     txts = [I18n.t( 'devise.registrations.signed_up'), I18n.t('devise.registrations.signed_up_but_unconfirmed')]
     expect(page).to have_content(/.*#{txts[0]}.*|.*#{txts[1]}.*/)
  end
```

This can be modified to fit every test in this spec file. See the modifications live here:
https://github.com/learn-co-students/devise_lab-v-000/compare/master...onyoo:master

**Comment by onyoo** [comment]
@jakebrady5 @Lukeghenco

**Comment by onyoo** [comment]
@frankNowinski

**Comment by victhevenot** [comment]
hey @onyoo 

Did some investigating and found a difference between our solution branch and the master tests. I'm going ahead and updating them. I do think you still have a bug in your code (this test is still failing) `Sign in user can sign in with valid credentials`, which is unrelated to the bug you found in our tests.

Thanks again!

**Comment by onyoo** [comment]
Thanks for checking it out! I will review my code ^^
