### ISSUE TITLE
Minimum Password Length

### ISSUE THREAD

**Issue by cboujoukos** [learn-co-curriculum/devise_lab#37]
Devise's default min characters for a password is 6 characters, and the test's "too short" password is 6 characters. It might be worthwhile to have the test try a password of 5 or less, or mention password requirements in the lab. Hope this helps!

**Comment by ThePeej** [comment]
Thanks for this. I had to update the test spec in spec/visitors/sign_up_spec.rb

line 40:
from
`sign_up_with('test@example.com', 'please', 'please')`

to
`sign_up_with('test@example.com', 'pleez', 'pleez')`

(or anything else below 6 characters)
