### ISSUE TITLE
the procedures for creating a FB login have now changed.

### ISSUE THREAD

**Issue by AdamKing0126** [learn-co-curriculum/devise_lab#8]
To create a FB login, the developer needs to "add product" and then select "facebook login."  That's were you put the callback address

**Comment by mendelB** [comment]
Hey @AdamKing0126 We've finally fixed and clarified this #23 
And we've merged a bunch of clarifying pull requests from students for this lab, so  hopefully y'all will be fielding less questions on this one :)
